import React from 'react';
import clsx from 'clsx';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';

const features = [
  {
    title: 'Make Shopping Easier',
    imageUrl: 'img/cart.png',
    description: (
      <>
        Make shopping as easy as chatting with a friend, Offer a unified experience across channels - in-store to website to various social media channels like FB, WA, etc, Pick up the pace from where you left last. Continue conversations across platforms with all the context
      </>
    ),
  },
  {
    title: "Never let a single trend go unnoticed",
    imageUrl: 'img/analytics.png',
    description: (
      <>
        Get closer to your customers by gathering insights generated by natural conversations, Spot red-flags and positive experiences immediately and take required measures, Derive value from insights and analytics from Day 1
      </>
    ),
  },
  {
    title: 'Redefine shopper’s experience with conversational commerce',
    imageUrl: 'img/Group-1.png',
    description: (
      <>
        Canary helps you manage your storefront, sales, marketing and customer engagement across channels, all from a single interface
      </>
    ),
  },
];

function Feature({ imageUrl, title, description }) {
  const imgUrl = useBaseUrl(imageUrl);
  return (
    <div className={clsx('col col--4', styles.feature)}>
      {imgUrl && (
        <div className="text--center">
          <img className={styles.featureImage} src={imgUrl} alt={title} />
        </div>
      )}
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  );
}

function Home() {
  const context = useDocusaurusContext();
  const { siteConfig = {} } = context;
  return (
    <Layout
      title={`Hello from ${siteConfig.title}`}
      description="Description will go into a meta tag in <head />">
      <header className={clsx('hero hero--primary', styles.heroBanner)}>
        <div className="container">
          <h1 className="hero__title">{siteConfig.title}</h1>
          <p className="hero__subtitle">{siteConfig.tagline}</p>
          <div className={styles.buttons}>
            <Link
              className={clsx(
                'button button--outline button--secondary button--lg',
                styles.getStarted,
              )}
              to={useBaseUrl('docs/')}>
              Get Started
            </Link>
          </div>
        </div>
      </header>
      <main>
        {features && features.length > 0 && (
          <section className={styles.features}>
            <div className="container">
              <div className="row">
                {features.map((props, idx) => (
                  <Feature key={idx} {...props} />
                ))}
              </div>
            </div>
          </section>
        )}
      </main>
    </Layout>
  );
}

export default Home;
